export const QUERY_TAGS = {
  VIP_RESTAURANTS: "VIP_RESTAURANTS",
  COUPONS: "COUPONS",
  RECEIPTS: "RECEIPTS",
  NOTIFICATIONS: "NOTIFICATIONS",
  RESTAURANTS: "RESTAURANTS",
  USER_LOYALTY: "USER_LOYALTY",
};
